package View;

import Model.player;
import Model.tabuleiro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author allan
 */
public class formTabuleiro extends javax.swing.JFrame {

    /**
     * Creates new form formTabuleiro
     */
    public formTabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1.setEnabled(false);
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });

        a2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a2.setEnabled(false);
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
        });

        a3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a3.setEnabled(false);
        a3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3MouseClicked(evt);
            }
        });

        b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1.setEnabled(false);
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });

        b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2.setEnabled(false);
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });

        b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3.setEnabled(false);
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });

        c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c1.setEnabled(false);
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });

        c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c2.setEnabled(false);
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });

        c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c3.setEnabled(false);
        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3MouseClicked(evt);
            }
        });

        jLabel1.setText("Pontuação:");

        jLabel2.setText("P1");

        jLabel3.setText("P2");

        lblP1.setText("0");
        lblP1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblP2.setText("0");
        lblP2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblP1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblP2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {a1, a2, a3, b1, b2, b3, c1, c2, c3});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblP1, lblP2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblP1)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblP2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {a1, a2, a3, b1, b2, b3, c1, c2, c3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblP1, lblP2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
       int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           a1.setText("X");
           seq.add(p2);
           tab.insert('X', 0, 0);
       }
       else{
           a1.setText("0");
           seq.add(p1);
           tab.insert('O', 0, 0);
       }
       a1.setEnabled(false);
       int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_a1MouseClicked

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        reset();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void reset(){
        String x = " ";
        seq.add(p1);
        a1.setText(x);
        a1.setEnabled(true);
        a2.setText(x);
        a2.setEnabled(true);
        a3.setText(x);
        a3.setEnabled(true);
        b1.setText(x);
        b1.setEnabled(true);
        b2.setText(x);
        b2.setEnabled(true);
        b3.setText(x);
        b3.setEnabled(true);
        c1.setText(x);
        c1.setEnabled(true);
        c2.setText(x);
        c2.setEnabled(true);
        c3.setText(x);
        c3.setEnabled(true);
        tab = new tabuleiro();
        lblP1.setText(String.valueOf(p1.getScore()));
        lblP2.setText(String.valueOf(p2.getScore()));
    }
    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
       int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           c2.setText("X");
           seq.add(p2);
           tab.insert('X', 2, 1);
       }
       else{
           c2.setText("0");
           seq.add(p1);
           tab.insert('O', 2, 1);
       }
       c2.setEnabled(false);
       int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
       
    }//GEN-LAST:event_c2MouseClicked

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
       int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           a2.setText("X");
           seq.add(p2);
           tab.insert('X', 0, 1);
       }
       else{
           a2.setText("0");
           seq.add(p1);
           tab.insert('O', 0, 1);
       }
       a2.setEnabled(false);
     int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_a2MouseClicked

    private void a3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseClicked
        int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           a3.setText("X");
           seq.add(p2);
           tab.insert('X', 0, 2);
       }
       else{
           a3.setText("0");
           seq.add(p1);
           tab.insert('O', 0, 2);
       }
       a3.setEnabled(false);
      int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_a3MouseClicked

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           b1.setText("X");
           seq.add(p2);
           tab.insert('X', 1, 0);
       }
       else{
           b1.setText("0");
           seq.add(p1);
           tab.insert('O', 1, 0);
       }
       b1.setEnabled(false);
      int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           b2.setText("X");
           seq.add(p2);
           tab.insert('X', 1, 1);
       }
       else{
           b2.setText("0");
           seq.add(p1);
           tab.insert('O', 1, 1);
       }
       b2.setEnabled(false);
       int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
       int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           b3.setText("X");
           seq.add(p2);
           tab.insert('X', 1, 2);
       }
       else{
           b3.setText("0");
           seq.add(p1);
           tab.insert('O', 1, 2);
       }
       b3.setEnabled(false);
       int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_b3MouseClicked

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
        int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           c1.setText("X");
           seq.add(p2);
           tab.insert('X', 2, 0);
       }
       else{
           c1.setText("0");
           seq.add(p1);
           tab.insert('O', 2, 0);
       }
       c1.setEnabled(false);
       int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_c1MouseClicked

    private void c3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseClicked
        int tam = seq.size();
       if(seq.get(tam-1).equals(p1)){
           c3.setText("X");
           seq.add(p2);
           tab.insert('X', 2, 2);
       }
       else{
           c3.setText("0");
           seq.add(p1);
           tab.insert('O', 2, 2);
       }
       c3.setEnabled(false);
       int v = tab.Verifica();
        switch (v) {
            case 1:
                p1.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 1 ganhou !!!");
                break;
            case 0:
                p2.UpdateScore();
                reset();
                JOptionPane.showMessageDialog(null, "Jogador 2 ganhou !!!");
                break;
            case 3:
                reset();
                JOptionPane.showMessageDialog(null, "Empate !!!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_c3MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTabuleiro().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    // End of variables declaration//GEN-END:variables
    player p1 = new player("p1");
    player p2 = new player("p2");   
    ArrayList<player> seq = new ArrayList<>();
    tabuleiro tab = new tabuleiro();
    
}
